没化yaml

diff --git a/kubens b/kubens
--- a/kubens
+++ b/kubens
@@ -43,16 +43,16 @@ EOF
 }
 
 exit_err() {
-   echo >&2 "${1}"
-   exit 1
+  echo >&2 "${1}"
+  exit 1
 }
 
 current_namespace() {
   local cur_ctx
 
   cur_ctx="$(current_context)" || exit_err "error getting current context"
-  ns="$($KUBECTL config view -o=jsonpath="{.contexts[?(@.name==\"${cur_ctx}\")].context.namespace}")" \
-     || exit_err "error getting current namespace"
+  ns="$($KUBECTL config view -o=jsonpath="{.contexts[?(@.name==\"${cur_ctx}\")].context.namespace}")" ||
+    exit_err "error getting current namespace"
 
   if [[ -z "${ns}" ]]; then
     echo "default"
@@ -94,14 +94,14 @@ save_namespace() {
   saved="$(read_namespace "${1}")"
 
   if [[ "${saved}" != "${2}" ]]; then
-    printf %s "${2}" > "${f}"
+    printf %s "${2}" >"${f}"
   fi
 }
 
 switch_namespace() {
   local ctx="${1}"
   $KUBECTL config set-context "${ctx}" --namespace="${2}"
-  echo "Active namespace is \"${2}\".">&2
+  echo "Active namespace is \"${2}\"." >&2
 }
 
 choose_namespace_interactive() {
@@ -137,7 +137,7 @@ set_namespace() {
       save_namespace "${ctx}" "${prev}"
     fi
   else
-    echo "error: no namespace exists with name \"${1}\".">&2
+    echo "error: no namespace exists with name \"${1}\"." >&2
     exit 1
   fi
 }
@@ -157,17 +157,17 @@ list_namespaces() {
   ns_list=$(get_namespaces) || exit_err "error getting namespace list"
 
   for c in $ns_list; do
-  if [[ -n "${_KUBECTX_FORCE_COLOR:-}" || \
-       -t 1 && -z "${NO_COLOR:-}" ]]; then
-    # colored output mode
-    if [[ "${c}" = "${cur}" ]]; then
-      echo "${cur_ctx_bg}${cur_ctx_fg}${c}${normal}"
+    if [[ -n "${_KUBECTX_FORCE_COLOR:-}" ||
+      -t 1 && -z "${NO_COLOR:-}" ]]; then
+      # colored output mode
+      if [[ "${c}" = "${cur}" ]]; then
+        echo "${cur_ctx_bg}${cur_ctx_fg}${c}${normal}"
+      else
+        echo "${c}"
+      fi
     else
       echo "${c}"
     fi
-  else
-    echo "${c}"
-  fi
   done
 }
 
@@ -186,7 +186,7 @@ main() {
   if [[ -z "${KUBECTL:-}" ]]; then
     if hash kubectl 2>/dev/null; then
       KUBECTL=kubectl
-    elif hash kubectl.exe  2>/dev/null; then
+    elif hash kubectl.exe 2>/dev/null; then
       KUBECTL=kubectl.exe
     else
       echo >&2 "kubectl is not installed"
@@ -195,7 +195,10 @@ main() {
   fi
 
   if [[ "$#" -eq 0 ]]; then
-    if [[ -t 1 && -z ${KUBECTX_IGNORE_FZF:-} && "$(type fzf &>/dev/null; echo $?)" -eq 0 ]]; then
+    if [[ -t 1 && -z ${KUBECTX_IGNORE_FZF:-} && "$(
+      type fzf &>/dev/null
+      echo $?
+    )" -eq 0 ]]; then
       choose_namespace_interactive
     else
       list_namespaces
